# Generated by Django 4.1.2 on 2023-02-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.SmallIntegerField(default=0)),
                ('number', models.SmallIntegerField(default=0, verbose_name='номер группы')),
                ('mentor_id', models.BigIntegerField(default=0)),
                ('date_start', models.DateField(blank=True, verbose_name='дата начала')),
                ('audience_id', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='юзер')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.group', verbose_name='номер группы')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='емайл')),
                ('password', models.CharField(max_length=128)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lesson.groupusers', verbose_name='ном пром груп')),
            ],
        ),
    ]
