# Generated by Django 4.1.2 on 2023-02-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_audience_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='audience_id',
            new_name='audience',
        ),
    ]
