# Generated by Django 4.1.2 on 2023-02-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_rename_audience_id_group_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='format_id',
        ),
        migrations.AlterField(
            model_name='audience',
            name='number',
            field=models.SmallIntegerField(default=0, verbose_name='номер аудитории'),
        ),
    ]
