# Generated by Django 4.1.2 on 2023-02-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_remove_audience_format_id_alter_audience_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='продолжительность обучения')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Training_Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=True, verbose_name='онлайн обучение')),
            ],
            options={
                'verbose_name': 'формат обучения',
                'verbose_name_plural': 'формат обучения',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='course_id',
        ),
        migrations.AddField(
            model_name='audience',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lesson.training_format', verbose_name=' формат обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lesson.course', verbose_name='курс'),
        ),
    ]
