# Generated by Django 4.1.2 on 2023-02-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_course_training_format_remove_group_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='lesson.groupusers', verbose_name='ном пром груп'),
            preserve_default=False,
        ),
    ]
